name: 中青签到

on:
  schedule:
    - cron: '0 0,5,6,21,23 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requests'
        run: pip install requests

      - name: 'run 中青看点签到'
        # qq_speed.py目录自己修改
        run: python youth_sign.py
